/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Monster Charment的博客",
  "description": "Monster Charment的博客",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "author",
        "content": "Monster Charment"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "Monster Charment的博客"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-bf08e8f0",
      "path": "/",
      "lastUpdated": "Monday, May 10, 2021 4:26 PM"
    },
    {
      "title": "关于我",
      "frontmatter": {
        "title": "关于我"
      },
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-52fdf81a",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1"
        },
        {
          "level": 3,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 2,
          "title": "一级标题2",
          "slug": "一级标题2"
        },
        {
          "level": 2,
          "title": "一级标题3",
          "slug": "一级标题3"
        },
        {
          "level": 2,
          "title": "一级标题4",
          "slug": "一级标题4"
        }
      ],
      "lastUpdated": "Monday, May 10, 2021 4:26 PM"
    },
    {
      "title": "CSS C",
      "frontmatter": {
        "title": "CSS C"
      },
      "regularPath": "/css/c-ccc.html",
      "relativePath": "css/c-ccc.md",
      "key": "v-103b8da6",
      "path": "/css/c-ccc.html",
      "lastUpdated": "Monday, May 10, 2021 4:26 PM"
    },
    {
      "title": "CSS A",
      "frontmatter": {
        "title": "CSS A"
      },
      "regularPath": "/css/c-aaa.html",
      "relativePath": "css/c-aaa.md",
      "key": "v-4f78b0e6",
      "path": "/css/c-aaa.html",
      "lastUpdated": "Monday, May 10, 2021 4:26 PM"
    },
    {
      "title": "CSS a",
      "frontmatter": {
        "title": "CSS a"
      },
      "regularPath": "/css/",
      "relativePath": "css/README.md",
      "key": "v-9518b5e6",
      "path": "/css/",
      "headers": [
        {
          "level": 2,
          "title": "你好 CSS",
          "slug": "你好-css"
        }
      ],
      "lastUpdated": "Monday, May 10, 2021 4:26 PM"
    },
    {
      "title": "J AAA",
      "frontmatter": {
        "title": "J AAA"
      },
      "regularPath": "/javascript/j-aaa.html",
      "relativePath": "javascript/j-aaa.md",
      "key": "v-7d148398",
      "path": "/javascript/j-aaa.html",
      "lastUpdated": "Monday, May 10, 2021 4:26 PM"
    },
    {
      "title": "J a",
      "frontmatter": {
        "title": "J a"
      },
      "regularPath": "/javascript/",
      "relativePath": "javascript/README.md",
      "key": "v-8309dd6a",
      "path": "/javascript/",
      "headers": [
        {
          "level": 2,
          "title": "你好 Javascript",
          "slug": "你好-javascript"
        }
      ],
      "lastUpdated": "Monday, May 10, 2021 4:26 PM"
    },
    {
      "title": "CSS B",
      "frontmatter": {
        "title": "CSS B"
      },
      "regularPath": "/css/c-bbb.html",
      "relativePath": "css/c-bbb.md",
      "key": "v-a04bc174",
      "path": "/css/c-bbb.html",
      "lastUpdated": "Monday, May 10, 2021 4:26 PM"
    },
    {
      "title": "J B",
      "frontmatter": {
        "title": "J B"
      },
      "regularPath": "/javascript/j-bbb.html",
      "relativePath": "javascript/j-bbb.md",
      "key": "v-e8252b9c",
      "path": "/javascript/j-bbb.html",
      "lastUpdated": "Monday, May 10, 2021 4:26 PM"
    },
    {
      "title": "J C",
      "frontmatter": {
        "title": "J C"
      },
      "regularPath": "/javascript/j-ccc.html",
      "relativePath": "javascript/j-ccc.md",
      "key": "v-56651630",
      "path": "/javascript/j-ccc.html",
      "lastUpdated": "Monday, May 10, 2021 4:26 PM"
    },
    {
      "title": "评论",
      "frontmatter": {
        "title": "评论"
      },
      "regularPath": "/message.html",
      "relativePath": "message.md",
      "key": "v-a25a4b1a",
      "path": "/message.html"
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/home/homegif.gif",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/guide/"
      },
      {
        "text": "About",
        "link": "/about.html"
      },
      {
        "text": "留言",
        "link": "/message.html"
      },
      {
        "text": "Languages",
        "ariaLabel": "Language Menu",
        "items": [
          {
            "text": "Chinese",
            "link": "/language/chinese/"
          },
          {
            "text": "Japanese",
            "link": "/language/japanese/"
          }
        ]
      }
    ],
    "sidebar": {
      "/css/": [
        "c-aaa",
        "c-bbb",
        "c-ccc"
      ],
      "/javascript/": [
        "j-aaa",
        "j-bbb",
        "j-ccc"
      ]
    }
  }
}