/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Monster Charment的博客",
  "description": "欢迎欢迎~~~",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "author",
        "content": "Monster Charment"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "Monster Charment的博客"
      }
    ],
    [
      "link",
      {
        "rel": "icon",
        "href": "favicon.ico"
      }
    ],
    [
      "script",
      {
        "language": "javascript",
        "type": "text/javascript",
        "src": "/js/jquery.min.js"
      }
    ],
    [
      "script",
      {
        "language": "javascript",
        "type": "text/javascript",
        "src": "/js/MouseClickEffect.js"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Monster Charment的博客",
        "tagline": "欢迎来到我的博客~",
        "readingShow": "top"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-bf08e8f0",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "",
          "slug": "countup-endval-2021"
        }
      ],
      "lastUpdated": "2021年5月14日星期五下午12点37分"
    },
    {
      "title": "CountUp 第三方组件",
      "frontmatter": {
        "title": "CountUp 第三方组件",
        "readingShow": "top"
      },
      "regularPath": "/countup.html",
      "relativePath": "countup.md",
      "key": "v-4c5f2a53",
      "path": "/countup.html",
      "lastUpdated": "2021年5月13日星期四晚上10点52分"
    },
    {
      "title": "评论",
      "frontmatter": {
        "title": "评论",
        "readingShow": "top"
      },
      "regularPath": "/message.html",
      "relativePath": "message.md",
      "key": "v-a25a4b1a",
      "path": "/message.html",
      "lastUpdated": "2021年5月13日星期四晚上9点20分"
    },
    {
      "title": "关于我和这个博客",
      "frontmatter": {
        "title": "关于我和这个博客",
        "description": "好像没啥用的description",
        "categories": [
          "about me and blog"
        ],
        "tags": [
          "about"
        ],
        "publish": true,
        "sticky": 1,
        "date": "2021-05-14T20:00:00.000Z",
        "readingShow": "top"
      },
      "regularPath": "/about/about.html",
      "relativePath": "about/about.md",
      "key": "v-7c2ac234",
      "path": "/about/about.html",
      "lastUpdated": "2021年5月14日星期五下午12点37分"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline",
        "readingShow": "top"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "about Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/about/",
      "key": "v-9a67fd28",
      "path": "/tag/about/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "about me and blog Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/about%20me%20and%20blog/",
      "key": "v-2903608a",
      "path": "/categories/about me and blog/"
    }
  ],
  "themeConfig": {
    "type": "blog",
    "author": "Monster Charment",
    "authorAvatar": "/avatar.jpg",
    "logo": "/assets/img/home/homegif.gif",
    "nav": [
      {
        "text": "主页",
        "icon": "reco-home",
        "link": "/"
      },
      {
        "text": "分类",
        "icon": "reco-category",
        "items": [
          {
            "text": "CSS",
            "link": "/"
          },
          {
            "text": "JavaScript",
            "link": "/"
          },
          {
            "text": "Vue",
            "link": "/"
          }
        ]
      },
      {
        "text": "时间线",
        "icon": "reco-date",
        "link": "/"
      },
      {
        "text": "项目",
        "icon": "reco-menu",
        "items": [
          {
            "text": "暂无~",
            "link": "/"
          }
        ]
      },
      {
        "text": "工具",
        "icon": "reco-tag",
        "items": [
          {
            "text": "git的使用",
            "link": "/"
          },
          {
            "text": "github",
            "link": "/"
          }
        ]
      },
      {
        "text": "关于",
        "icon": "reco-account",
        "items": [
          {
            "text": "关于我",
            "link": "/about/about.html"
          },
          {
            "text": "关于博客",
            "link": "/"
          }
        ]
      },
      {
        "text": "留言",
        "icon": "reco-message",
        "link": "/message.html"
      },
      {
        "text": "github",
        "icon": "reco-github",
        "items": [
          {
            "text": "我的github",
            "link": "https://github.com/aa1050532409"
          }
        ]
      }
    ],
    "sidebar": {},
    "noFoundPageByTencent": false
  }
}