/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Monster Charment的博客",
  "description": "欢迎欢迎~~~",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "author",
        "content": "Monster Charment"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "Monster Charment的博客"
      }
    ],
    [
      "link",
      {
        "rel": "icon",
        "href": "favicon.ico"
      }
    ],
    [
      "script",
      {
        "language": "javascript",
        "type": "text/javascript",
        "src": "/js/jquery.min.js"
      }
    ],
    [
      "script",
      {
        "language": "javascript",
        "type": "text/javascript",
        "src": "/js/MouseClickEffect.js"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Monster Charment的博客",
        "tagline": "欢迎来到我的博客~",
        "readingShow": "top"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-713ca0e0",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "",
          "slug": "countup-endval-2021"
        }
      ],
      "lastUpdated": "2021年5月17日星期一上午9点02分"
    },
    {
      "title": "关于我和这个博客",
      "frontmatter": {
        "title": "关于我和这个博客",
        "description": "好像没啥用的description",
        "categories": [
          "about me and blog"
        ],
        "tags": [
          "about"
        ],
        "publish": true,
        "sticky": 1,
        "date": "2021-05-14T20:00:00.000Z",
        "readingShow": "top"
      },
      "regularPath": "/about/about.html",
      "relativePath": "about/about.md",
      "key": "v-0930cfde",
      "path": "/about/about.html",
      "lastUpdated": "2021年5月14日星期五晚上11点05分"
    },
    {
      "title": "评论",
      "frontmatter": {
        "title": "评论",
        "readingShow": "top"
      },
      "regularPath": "/message.html",
      "relativePath": "message.md",
      "key": "v-a614f92a",
      "path": "/message.html",
      "lastUpdated": "2021年5月13日星期四晚上9点20分"
    },
    {
      "title": "CountUp 第三方组件",
      "frontmatter": {
        "title": "CountUp 第三方组件",
        "readingShow": "top"
      },
      "regularPath": "/countup.html",
      "relativePath": "countup.md",
      "key": "v-4a81d34b",
      "path": "/countup.html",
      "lastUpdated": "2021年5月14日星期五晚上11点05分"
    },
    {
      "title": "git的使用",
      "frontmatter": {
        "title": "git的使用",
        "description": "好像没啥用的description",
        "categories": [
          "git"
        ],
        "tags": [
          "git's use"
        ],
        "publish": true,
        "date": "2021-05-15T23:30:00.000Z",
        "readingShow": "top"
      },
      "regularPath": "/blogs/git/git.html",
      "relativePath": "blogs/git/git.md",
      "key": "v-7628dc11",
      "path": "/blogs/git/git.html",
      "lastUpdated": "2021年5月16日星期日凌晨12点16分"
    },
    {
      "title": "http端口号80占用问题解决",
      "frontmatter": {
        "title": "http端口号80占用问题解决",
        "description": "好像没啥用的description",
        "categories": [
          "node"
        ],
        "tags": [
          "http"
        ],
        "publish": true,
        "date": "2021-05-19T11:00:00.000Z",
        "readingShow": "top"
      },
      "regularPath": "/blogs/node/http_port/http_port.html",
      "relativePath": "blogs/node/http_port/http_port.md",
      "key": "v-59d10c40",
      "path": "/blogs/node/http_port/http_port.html"
    },
    {
      "title": "跨域的解决",
      "frontmatter": {
        "title": "跨域的解决",
        "description": "好像没啥用的description",
        "categories": [
          "vue"
        ],
        "tags": [
          "cross-domain"
        ],
        "publish": true,
        "date": "2021-05-17T10:00:00.000Z",
        "readingShow": "top"
      },
      "regularPath": "/blogs/vue/crossDomain.html",
      "relativePath": "blogs/vue/crossDomain.md",
      "key": "v-27875451",
      "path": "/blogs/vue/crossDomain.html",
      "lastUpdated": "2021年5月17日星期一上午10点44分"
    },
    {
      "title": "天气查询",
      "frontmatter": {
        "title": "天气查询",
        "readingShow": "top"
      },
      "regularPath": "/weatherMonc.html",
      "relativePath": "weatherMonc.md",
      "key": "v-4f7a3f6b",
      "path": "/weatherMonc.html",
      "lastUpdated": "2021年5月17日星期一上午9点02分"
    }
  ],
  "themeConfig": {
    "type": "blog",
    "author": "Monster Charment",
    "authorAvatar": "/avatar.jpg",
    "logo": "/assets/img/home/homegif.gif",
    "nav": [
      {
        "text": "主页",
        "icon": "reco-home",
        "link": "/"
      },
      {
        "text": "分类",
        "icon": "reco-category",
        "items": [
          {
            "text": "CSS",
            "link": "/"
          },
          {
            "text": "JavaScript",
            "link": "/"
          },
          {
            "text": "Vue",
            "link": "/"
          }
        ]
      },
      {
        "text": "时间线",
        "icon": "reco-date",
        "link": "/"
      },
      {
        "text": "项目",
        "icon": "reco-menu",
        "items": [
          {
            "text": "暂无~",
            "link": "/"
          }
        ]
      },
      {
        "text": "工具",
        "icon": "reco-tag",
        "items": [
          {
            "text": "git的使用",
            "link": "/blogs/git/git.html"
          },
          {
            "text": "github",
            "link": "/"
          }
        ]
      },
      {
        "text": "关于",
        "icon": "reco-account",
        "items": [
          {
            "text": "关于我",
            "link": "/about/about.html"
          },
          {
            "text": "关于博客",
            "link": "/"
          }
        ]
      },
      {
        "text": "留言",
        "icon": "reco-message",
        "link": "/message.html"
      },
      {
        "text": "github",
        "icon": "reco-github",
        "items": [
          {
            "text": "我的github",
            "link": "https://github.com/aa1050532409"
          }
        ]
      }
    ],
    "sidebar": {},
    "noFoundPageByTencent": false,
    "lastUpdated": "更新时间"
  }
}