/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "about": {
      "key": "about",
      "scope": "tags",
      "path": "/tag/about/",
      "pageKeys": [
        "v-7c2ac234"
      ]
    }
  },
  "categories": {
    "about me and blog": {
      "key": "about me and blog",
      "scope": "categories",
      "path": "/categories/about me and blog/",
      "pageKeys": [
        "v-7c2ac234"
      ]
    }
  },
  "timeline": {}
}