/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "about": {
      "key": "about",
      "scope": "tags",
      "path": "/tag/about/",
      "pageKeys": [
        "v-0930cfde"
      ]
    },
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tag/vue/",
      "pageKeys": [
        "v-27875451"
      ]
    },
    "cross-domain": {
      "key": "cross-domain",
      "scope": "tags",
      "path": "/tag/cross-domain/",
      "pageKeys": [
        "v-27875451"
      ]
    },
    "http": {
      "key": "http",
      "scope": "tags",
      "path": "/tag/http/",
      "pageKeys": [
        "v-59d10c40"
      ]
    },
    "git": {
      "key": "git",
      "scope": "tags",
      "path": "/tag/git/",
      "pageKeys": [
        "v-7628dc11"
      ]
    }
  },
  "categories": {
    "about me and blog": {
      "key": "about me and blog",
      "scope": "categories",
      "path": "/categories/about me and blog/",
      "pageKeys": [
        "v-0930cfde"
      ]
    },
    "vue": {
      "key": "vue",
      "scope": "categories",
      "path": "/categories/vue/",
      "pageKeys": [
        "v-27875451"
      ]
    },
    "http": {
      "key": "http",
      "scope": "categories",
      "path": "/categories/http/",
      "pageKeys": [
        "v-59d10c40"
      ]
    },
    "git's use": {
      "key": "git's use",
      "scope": "categories",
      "path": "/categories/git's use/",
      "pageKeys": [
        "v-7628dc11"
      ]
    }
  },
  "timeline": {}
}