/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "about",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/about/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "git",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/git/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "about me and blog",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/about me and blog/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "git's use",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/git's use/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
}]